# Generated by Django 3.2.3 on 2022-05-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0002_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='verifylogin',
        ),
    ]
