# Generated by Django 3.2.3 on 2022-05-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0003_rename_login_verifylogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(default=0, max_length=10)),
                ('tname', models.CharField(max_length=100)),
                ('tdob', models.DateField()),
                ('tmob', models.IntegerField(default=0)),
                ('dptname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='adnum',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
