# Generated by Django 3.2.3 on 2022-05-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0004_auto_20220509_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.CharField(default=0, max_length=10)),
                ('hname', models.CharField(max_length=100)),
                ('hdob', models.DateField()),
                ('hmob', models.IntegerField(default=0)),
                ('hdpt', models.CharField(max_length=100)),
            ],
        ),
    ]
