# Generated by Django 3.2.3 on 2022-05-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0006_auto_20220513_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
