# Generated by Django 3.2.3 on 2022-05-14 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0007_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='swaapp.verifylogin')),
            ],
        ),
    ]
