# Generated by Django 3.2.3 on 2022-05-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
