# Generated by Django 3.2.3 on 2022-05-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0009_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sdptname',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
