# Generated by Django 3.2.3 on 2022-05-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0010_student_sdptname'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semno',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
