# Generated by Django 3.2.3 on 2022-05-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0011_student_semno'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='simage',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
