# Generated by Django 3.2.3 on 2022-05-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0013_auto_20220523_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anid', models.CharField(max_length=10)),
                ('anmsg', models.CharField(max_length=50)),
                ('dptname', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matid', models.CharField(max_length=20)),
                ('material', models.FileField(upload_to='')),
                ('semno', models.CharField(max_length=20)),
                ('dptname', models.CharField(max_length=20)),
                ('subcode', models.CharField(max_length=20)),
                ('about', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='images',
        ),
        migrations.AddField(
            model_name='hod',
            name='himage',
            field=models.FileField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='simage',
            field=models.FileField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='timage',
            field=models.FileField(default=0, upload_to=''),
        ),
    ]
