# Generated by Django 3.2.3 on 2022-06-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0015_remove_announcement_anid'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10)),
                ('toflogin', models.DateTimeField()),
            ],
        ),
    ]
