# Generated by Django 3.2.3 on 2022-06-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0016_loginstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdpt', models.CharField(max_length=10)),
                ('subcode', models.CharField(max_length=10)),
                ('subsemno', models.IntegerField(max_length=10)),
                ('subteach', models.CharField(max_length=10)),
                ('subteachid', models.CharField(max_length=10)),
            ],
        ),
    ]
