# Generated by Django 3.2.3 on 2022-06-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0017_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subname',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
