# Generated by Django 3.2.3 on 2022-06-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0018_subject_subname'),
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('workid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dptname', models.CharField(max_length=45)),
                ('semno', models.CharField(max_length=10)),
                ('subname', models.CharField(max_length=45)),
                ('defwork', models.CharField(blank=True, max_length=45, null=True)),
                ('wfile', models.FileField(default=0, upload_to='')),
                ('sdate', models.DateField(blank=True, null=True)),
                ('edate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
