# Generated by Django 3.2.3 on 2022-06-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0019_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.CharField(max_length=10)),
                ('teach_id', models.CharField(max_length=10)),
                ('quest', models.CharField(max_length=50)),
            ],
        ),
    ]
