# Generated by Django 3.2.3 on 2022-06-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0021_auto_20220623_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatting',
            name='stud_name',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
