# Generated by Django 3.2.3 on 2022-06-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0022_chatting_stud_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatting',
            name='replay',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
