# Generated by Django 3.2.3 on 2022-06-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0023_chatting_replay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatting',
            name='id',
        ),
        migrations.AddField(
            model_name='chatting',
            name='chatid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
