# Generated by Django 3.2.3 on 2022-06-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0026_sworks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sworks',
        ),
    ]
