# Generated by Django 3.2.3 on 2022-06-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0027_delete_sworks'),
    ]

    operations = [
        migrations.CreateModel(
            name='sworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workid', models.CharField(max_length=3)),
                ('sid', models.CharField(max_length=5)),
                ('udate', models.DateTimeField(blank=True, null=True)),
                ('sfile', models.FileField(default=0, upload_to='')),
            ],
        ),
    ]
