# Generated by Django 3.2.3 on 2022-06-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0030_sworks_sname'),
    ]

    operations = [
        migrations.CreateModel(
            name='year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('tutor', models.CharField(max_length=10)),
                ('createbt', models.CharField(max_length=10)),
            ],
        ),
    ]
