# Generated by Django 3.2.3 on 2022-06-27 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0031_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='year',
            new_name='ayear',
        ),
    ]
