# Generated by Django 3.2.3 on 2022-06-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0034_auto_20220628_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
