# Generated by Django 3.2.3 on 2022-06-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0035_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subcredit',
            field=models.CharField(default=4, max_length=10),
        ),
    ]
