# Generated by Django 3.2.3 on 2022-06-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0036_subject_subcredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='submap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=10)),
                ('subname', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('stime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
