# Generated by Django 3.2.3 on 2022-06-29 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0037_submap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submap',
            old_name='tid',
            new_name='userid',
        ),
    ]
