# Generated by Django 3.2.3 on 2022-06-29 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0038_rename_tid_submap_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submap',
            old_name='userid',
            new_name='uid',
        ),
    ]
