# Generated by Django 3.2.3 on 2022-06-29 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0039_rename_userid_submap_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submap',
            name='uid',
        ),
    ]
