# Generated by Django 3.2.3 on 2022-06-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0040_remove_submap_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='submap',
            name='userid',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
