# Generated by Django 3.2.3 on 2022-06-29 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0041_submap_userid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='submap',
            new_name='substatus',
        ),
    ]
