# Generated by Django 3.2.3 on 2022-06-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0042_rename_submap_substatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substatus',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
