# Generated by Django 3.2.3 on 2022-06-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0043_alter_substatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='workname',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
