# Generated by Django 3.2.3 on 2022-06-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0045_sworks_wname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materials',
            old_name='about',
            new_name='subname',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='dptname',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='matid',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='semno',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='subcode',
        ),
        migrations.AlterField(
            model_name='materials',
            name='material',
            field=models.FileField(default=0, upload_to=''),
        ),
    ]
