# Generated by Django 3.2.3 on 2022-06-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0046_auto_20220629_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=0, max_length=20)),
                ('gpoint', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='grading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10)),
                ('sid', models.CharField(max_length=10)),
                ('wname', models.CharField(max_length=10)),
                ('rating', models.CharField(max_length=10)),
                ('tofgrd', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.CharField(max_length=10)),
            ],
        ),
    ]
