# Generated by Django 3.2.3 on 2022-06-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0047_grade_grading'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('subname', models.CharField(max_length=50)),
                ('wname', models.CharField(max_length=50)),
                ('mark', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
