# Generated by Django 3.2.3 on 2022-06-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0048_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
