# Generated by Django 3.2.3 on 2022-06-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0049_alter_marks_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='creditreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semno', models.CharField(max_length=50)),
                ('creditallo', models.CharField(max_length=50)),
                ('creditmin', models.CharField(max_length=50)),
            ],
        ),
    ]
