# Generated by Django 3.2.3 on 2022-06-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0050_creditreq'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('feedback', models.CharField(max_length=50)),
                ('toffb', models.DateTimeField(null=True)),
            ],
        ),
    ]
