# Generated by Django 3.2.3 on 2022-06-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaapp', '0051_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=50)),
                ('dptname', models.CharField(max_length=20)),
                ('semno', models.CharField(max_length=10)),
            ],
        ),
    ]
