from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('addstud/', views.addstud, name='addstud'),
    path('add_stud/', views.add_stud, name='add_stud'),
    path('add_teach/',views.add_teach, name='add_teach'),
    path('add_hod',views.add_hod, name='add_hod'),
    path('addwork/',views.addwork, name='addwork'),
    path('add_work/',views.add_work, name='add_work'),
    path('teachhome/', views.teachhome, name='teachhome'),
    path('hodhome', views.hodhome, name='hodhome'),
    path('adminhome', views.adminhome, name='adminhome'),
    path('', views.login_view,name='login_view'),
    path('loginview',views.loginview,name='loginview'),
    path('addteach',views.addteach,name='addteach'),
    path('addhod',views.addhod,name='addhod'),
    path('showstud/',views.showstud,name='showstud'),
    path('changpass/',views.changpass,name='changpass'),
    path('studli/',views.studli,name='studli'),
    path('ancmnts/',views.ancmnts,name='ancmnts'),
    path('add_ancm/',views.add_ancm,name='add_ancm'),
    path('shome/',views.shome,name='shome'),
    path('stud_profile/',views.stud_profile,name='stud_profile'),
    path('teach_profile/',views.teach_profile,name='teach_profile'),
    path('smenu/',views.smenu,name='smenu'),
    path('add_sub/',views.add_sub,name='add_sub'),
    path('sub_map/',views.sub_map,name='sub_map'),
    path('submap/',views.submap,name='submap'),
    path('addsub/',views.addsub,name='addsub'),
    path('course/<str:subname>',views.course,name='course'),
    path('chattstud/<str:subteachid>',views.chattstud,name='chattstud'),
    path('chatreplay/<int:chatid>',views.chatreplay,name='chatreplay'),
    path('showchat/',views.showchat,name='showchat'),
    path('viewcourse/',views.viewcourse,name='viewcourse'),
    path('uploadwork/<int:workid>',views.uploadwork,name='uploadwork'),
    path('editstud/<int:adnum>',views.editstud,name='editstud'),
    path('gradings/',views.gradings,name='gradings'),
    path('workes/',views.workes,name='works'),
    path('addtutor/',views.addtutor,name='addtutor'),
    path('add_tutor/',views.add_tutor,name='add_tutor'),
    path('sgpa/',views.sgpa,name='sgpa'),
    path('view_credit/',views.view_credit,name='view_credit'),
    path('addmark/',views.addmark,name='addmark'),
    path('view_works/',views.view_works,name='view_works'),
    path('show_works/',views.show_works,name='show_works'),
    path('show_files/',views.show_files,name='show_files'),
    path('add_mark/',views.add_mark,name='add_mark'),
    path('liveclass/',views.liveclass,name='liveclass'),
    path('add_mater/',views.add_mater,name='add_mater'),
    path('addmater/',views.addmater,name='addmater'),
    path('show_file/',views.show_file,name='showfile'),
    path('add_grade/',views.add_grade,name='add_grade'),
    path('viewcredit/',views.viewcredit,name='viewcredit'),
    path('showmarks/',views.showmarks,name='showmarks'),
    path('addfeedback/',views.addfeedback,name='addfedback'),
    path('add_feedback/',views.add_feedback,name='add_feedback'),
    path('update_stud/',views.update_stud,name='update_stud'),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)